name: Test
on:
    push:
      branches: [master]
    pull_request:
      types: [opened, synchronize]
jobs:
  test:
    name: Run linters and tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
    - name: Run linters
      run: |
        flake8 .
    - name: Run tests
      run: |
        python -m unittest discover tests
